# Auto-label PRs based on changed files

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'
    - any-glob-to-any-file: 'frontend/**/*.js'
    - any-glob-to-any-file: 'frontend/**/*.jsx'
    - any-glob-to-any-file: 'frontend/**/*.ts'
    - any-glob-to-any-file: 'frontend/**/*.tsx'
    - any-glob-to-any-file: 'frontend/**/*.css'

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'
    - any-glob-to-any-file: 'backend/**/*.js'
    - any-glob-to-any-file: 'backend/**/*.ts'

python:
  - changed-files:
    - any-glob-to-any-file: 'python-service/**/*'
    - any-glob-to-any-file: '**/*.py'

docs:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**/*'

infra:
  - changed-files:
    - any-glob-to-any-file: 'docker-compose.yml'
    - any-glob-to-any-file: '**/Dockerfile'
    - any-glob-to-any-file: '.github/workflows/**'
    - any-glob-to-any-file: '.github/dependabot.yml'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'
    - any-glob-to-any-file: '**/*.test.js'
    - any-glob-to-any-file: '**/*.test.ts'
    - any-glob-to-any-file: '**/*.spec.js'
    - any-glob-to-any-file: '**/*.spec.ts'
    - any-glob-to-any-file: '**/*.test.py'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'package-lock.json'
    - any-glob-to-any-file: '**/package.json'
    - any-glob-to-any-file: '**/package-lock.json'
    - any-glob-to-any-file: '**/requirements.txt'
    - any-glob-to-any-file: '**/requirements*.txt'
    - any-glob-to-any-file: 'pyproject.toml'
